
services:
  db:
    image: postgres:16-alpine
    restart: "on-failure"
    container_name: saas_database
    env_file:
        - .env
  
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cloudmesh" ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
